version: '3.8'

services:
  app:
    build: .
    image: udk/app:development
    environment: &default
      FLASK_ENV: development
      MYSQL_DATABASE: udk
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    tty: true
    stdin_open: true
    depends_on:
      - mysql
    ports:
      - '5000:5000'
    volumes:
      - .:/usr/src/udk

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      <<: *default
    # ports:
    #   # <Port exposed> : < MySQL Port running inside container>
    #   - '3306:3306'
    # expose:
    #   # Opens port 3306 on the container
    #   - '3306'
    #   # Where our data will be persisted
    volumes:
      - db-data:/var/lib/mysql

  client:
    build: ./client
    image: udk/client:development
    environment:
      <<: *default
      NODE_ENV: development
      VUE_APP_API_HOST_URL: http://localhost:5000
    ports:
      - '8080:8080'
    volumes:
      - ./client:/usr/src/udk

  test:
    image: udk/app:development
    command: /bin/true
    environment:
      <<: *default
      FLASK_ENV: test
      MYSQL_DATABASE: udk_test
    tty: true
    stdin_open: true
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/udk

# Names our volume
volumes:
  db-data:
