version: '3.8'

services:
  app:
    depends_on:
      - mysql
    build: .
    tty: true
    stdin_open: true
    env_file: .env
    environment: &default
      FLASK_ENV: development
      DATABASE_NAME: udk
      DATABASE_USER: root
      DATABASE_PASSWORD: root
    ports:
      - '5000:5000'

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env
    environment:
      <<: *default
      MYSQL_ROOT_PASSWORD: root
