version: '3.8'

services:
  app:
    depends_on:
      - mysql
      - ui
    build: .
    tty: true
    stdin_open: true
    environment: &default
      FLASK_ENV: development
      MYSQL_DATABASE: udk
      # So you don't have to use root, but you can if you like
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '5000:5000'
    volumes:
      - type: bind
        source: .
        target: /usr/src/app

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      <<: *default
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - my-db:/var/lib/mysql

  ui:
    build: ./ui
    environment:
      <<: *default
      NODE_ENV: development
      VUE_APP_API_HOST_URL: http://localhost:5000
    ports:
      - '8080:8080'
    volumes:
      - ./ui:/usr/src/app

# Names our volume
volumes:
  my-db:
