class Buildings:
    Human = {
        "House": {"Singular": "Homestead",
                  "Plural": "Homesteads",
                  "Gold": 65,
                  "Wood": 20,
                  "Stone": 0,
                  "Output": 5,
                  "Description": "Each percent of land increases your birth rate by {0}%."},
        "Field": {"Singular": "Wheat Field",
                  "Plural": "Wheat Fields",
                  "Gold": 50,
                  "Wood": 10,
                  "Stone": 0,
                  "Output": 40,
                  "Description": "Provides enough grain to feed {0} people a day."},
        "Pasture": {"Singular": "Dairy Farm",
                    "Plural": "Dairy Farm",
                    "Gold": 75,
                    "Wood": 20,
                    "Stone": 0,
                    "Output": 60,
                    "Description": "Produces enough food to feed {0} people a day, but excess dairy is lost each day."},
    }
    Elf = {
        "House": {"Singular": "Sanctuary",
                  "Plural": "Sanctuaries",
                  "Gold": 65,
                  "Wood": 20,
                  "Stone": 0,
                  "Output": 5,
                  "Description": "Each percent of land increases your birth rate by {0}%."},
        "Field": {"Singular": "Rice Field",
                  "Plural": "Rice Fields",
                  "Gold": 50,
                  "Wood": 10,
                  "Stone": 0,
                  "Output": 40,
                  "Description": "Provides enough grain to feed {0} people a day."},
        "Pasture": {"Singular": "Dairy Pasture",
                    "Plural": "Dairy Pastures",
                    "Gold": 75,
                    "Wood": 20,
                    "Stone": 0,
                    "Output": 60,
                    "Description": "Produces enough food to feed {0} people a day, but excess dairy is lost each day."},
    }
