version: '3.8'

services:
  app:
    image: undying-kingdoms/ui:development
    build: .
    environment:
      NODE_ENV: development
    ports:
      - '8080:8080'
    volumes:
      - .:/usr/src/app
